### ISSUE TITLE
module serial has no attribute "Serial"

### ISSUE THREAD

**Issue by fredzannarbor** [Krupskis/xiao-firmware-binary#2]
```
python flash.py /dev/tty.usbmodem14101
Compass update failed with error:
module 'serial' has no attribute 'Serial'
```

This is most likely due to an incorrect port. Please check the port, but also don't hesitate to contact us - we can help!

```
ls /dev/tty.*
/dev/tty.BLTH
/dev/tty.Bluetooth-Incoming-Port
/dev/tty.D30
/dev/tty.usbmodem14101
```

pipgrep serial
serial==0.0.97

Python 3.10.9 (main, Dec 15 2022, 18:25:35) [Clang 14.0.0 (clang-1400.0.29.202)] on darwin

**Comment by Krupskis** [comment]
Hi @fredzannarbor, the required packaged is `pyserial`, not `serial`: [Read more](https://stackoverflow.com/a/47016463)

will update the docs
