### ISSUE TITLE
bad cpu type in adafruit (intel chip)

### ISSUE THREAD

**Issue by fredzannarbor** [Krupskis/xiao-firmware-binary#3]
```
/Users/fred/.virtualenvs/bookpublisherGPT/lib/python3.10/site-packages/serial/__init__.py
Compass update failed with error:
**[Errno 86] Bad CPU type in executable: './adafruit-nrfutil'**

This is most likely due to an incorrect port. Please check the port, but also don't hesitate to contact us - we can help!
```
Intel chip
 
    Hardware Overview:

      Model Name: MacBook Pro
      Model Identifier: MacBookPro16,1
      Processor Name: 6-Core Intel Core i7
      Processor Speed: 2.6 GHz
      Number of Processors: 1
      Total Number of Cores: 6
      L2 Cache (per Core): 256 KB
      L3 Cache: 12 MB
      Hyper-Threading Technology: Enabled
      Memory: 16 GB
      System Firmware Version: 2020.61.1.0.0 (iBridge: 21.16.2057.0.0,0)
      OS Loader Version: 580~1053
      Serial Number (system): C02CL4JCMD6M
      Hardware UUID: E287B880-EAA7-5CCE-AFFB-D782D9ACFE73
      Provisioning UDID: E287B880-EAA7-5CCE-AFFB-D782D9ACFE73
      Activation Lock Status: Enabled

**Comment by Krupskis** [comment]
I built the `adafruit-nrfutil` using an M-series macbook, that's probably the reason for the issue.

If you don't mind doing a bit of extra work try installing https://github.com/adafruit/Adafruit_nRF52_nrfutil on your platform and use that `adafruit-nrfutil` binary instead of the one provided.

**Comment by fredzannarbor** [comment]
python flash.py /dev/tty.usbmodem14101
/Users/fred/.virtualenvs/bookpublisherGPT/lib/python3.10/site-packages/serial/__init__.py
Upgrading target on /dev/tty.usbmodem14101 with DFU package /Users/fred/bin/Hardware-Guide/mac_updates/XIAO-ARDUINO-BLE.ino.zip. Flow control is disabled, Single bank, Touch disabled
Opened serial port /dev/tty.usbmodem14101
Starting DFU upgrade of type 4, SoftDevice size: 0, bootloader size: 0, application size: 124088
Sending DFU start packet
Sending DFU init packet
Sending firmware file
########################################
########################################
########################################
########################################
########################################
########################################
###
Activating new firmware

DFU upgrade took 8.06761908531189s
Device programmed.
Compass updated successfully.
