### ISSUE TITLE
Mac privacy => "abort trap 6"

### ISSUE THREAD

**Issue by fredzannarbor** [Krupskis/xiao-firmware-binary#4]
```
python transcribe.py
Abort trap: 6
```
 _see below for apple explanation, looks easy enough to fix_
------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               Python [31156]
Path:                  /usr/local/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/Resources/Python.app/Contents/MacOS/Python
Identifier:            org.python.python
Version:               3.10.9 (3.10.9)
Code Type:             X86-64 (Native)
Parent Process:        bash [20364]
Responsible:           stable [63409]
User ID:               501

Date/Time:             2024-05-08 06:09:53.0763 -0400
OS Version:            macOS 14.2.1 (23C71)
Report Version:        12
Bridge OS Version:     8.2 (21P2057)
Anonymous UUID:        D9322169-2B1A-836C-5143-457A89BE735D

Sleep/Wake UUID:       45E3EB9B-C035-4C5D-A00C-848822223D42

Time Awake Since Boot: 970000 seconds
Time Since Wake:       4045 seconds

System Integrity Protection: enabled

Crashed Thread:        6  Dispatch queue: com.apple.root.default-qos

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000

**Termination Reason:    Namespace TCC, Code 0 
This app has crashed because it attempted to access privacy-sensitive data without a usage description. The app's Info.plist must contain an NSBluetoothAlwaysUsageDescription key with a string value explaining to the user how the app uses this data.**

**Comment by Krupskis** [comment]
Can you try giving bluetooth permissions to the terminal app? Like this https://github.com/orgs/pybricks/discussions/583#discussioncomment-1933666

**Comment by fredzannarbor** [comment]
Making progress:
```

python transcribe.py
Could not find the compass device. Try restarting the wearable.
python transcribe.py
disconnected
Error: disconnected
```

What do I press/what do I expect to connect the device to Bluetooth? Can the device be plugged into the USB cord and charging?

**Comment by Krupskis** [comment]
it can be charging, as long as you can connect it using the app, you should be able to use the script.

**Comment by Krupskis** [comment]
To be completely sure, you could download `NRF Connect App` on your phone and see a bluetooth device named `Compass` is discoverable

**Comment by Krupskis** [comment]
@fredzannarbor what macOS are you running? `Bleak` seems to have issues with macOS 12 https://github.com/hbldh/bleak/issues/635

**Comment by Krupskis** [comment]
@fredzannarbor i pushed a new update to the script, can you try again?

**Comment by fredzannarbor** [comment]
will do
---
Fred Zimmerman, Publisher
Nimble Books LLC
The AI Lab for Book-Lovers <http://NimbleBooks.com>

**Comment by fredzannarbor** [comment]
Fiddled around for a while, got it working. Cool!

```
Audio data written to output.wav
Confidence: 0.98447347
transcription:
K.
Yeah, Parker.
God bless you.
I love you very much
```.

**Comment by Krupskis** [comment]
@fredzannarbor sweet! curious how you solved it in case others run into a similar issue?
